CREATE SCHEMA JUKEBOX_SCHEMA AUTHORIZATION SA;

use JUKEBOX_SCHEMA;

CREATE TABLE artist (
    id   INTEGER   PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    bio VARCHAR(255),
    fan_number INTEGER
);

CREATE TABLE album (
    id   INTEGER   PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    release_date DATE,
    fan_number INTEGER
);